[tool.poetry]
name = "alto2txt2fixture"
version = "0.1.0"
description = ""
authors = ["Kalle Westerling <kalle.westerling@bl.uk>"]

[tool.poetry.dependencies]
python = "^3.11"
tqdm = "^4.65.0"
pandas = "^2.0.3"
colorama = "^0.4.6"
numpy = "^1.25.0"
pytz = "^2022.7.1"
rich = "^12.6.0"
types-pytz = "^2023.3.0.0"

[tool.poetry.group.dev.dependencies]
pytest-sugar = "^0.9.7"
ipython = "^8.14.0"
pytest-cov = "^4.1.0"
mkdocs-material = "^9.1.18"
pre-commit = "^3.3.3"
mkdocs-gen-files = "^0.5.0"
mkdocs-section-index = "^0.3.5"
mkdocs-literate-nav = "^0.6.0"
mkdocstrings-python = "^1.1.2"
mypy = "^1.4.1"

[tool.isort]
profile = "black"

[tool.pycln]
all = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
a2t2f-news = "alto2txt2fixture.__main__:main"
a2tsf-adj = "alto2txt2fixture.create_adjacent_tables:run"

[tool.pytest.ini_options]
xfail_strict = true
addopts = """
--cov=alto2txt2fixture
--cov-report=term:skip-covered
--pdbcls=IPython.terminal.debugger:TerminalPdb
--doctest-modules
--durations=3
"""
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.mypy]
python_version = "3.11"
# check_untyped_defs = True
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_return_any = true
# plugins = [
# ]
#
# [[tool.mypy.overrides]]
# module = "*.migrations.*"
# ignore_errors = true
